<?php

use Illuminate\Database\Migrations\Migration;

/**
 * Duplicate Sanctum migration — intentionally empty.
 * The personal_access_tokens table is already created by
 * 2026_05_11_132124_create_personal_access_tokens_table.php.
 * This file was generated by a second accidental vendor:publish call.
 */
return new class extends Migration
{
    public function up(): void
    {
        // No-op: table already handled by the earlier migration file.
    }

    public function down(): void
    {
        // No-op: do not drop — the other migration's down() handles it.
    }
};
